import Nav from "@/components/Nav";
import "./globals.css";

import PageTransition from "@/components/PageTransition";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PageTransition>

        
        <Nav />
        {children}
        </PageTransition>
        </body>
    </html>
  );
}
